file_list = ['AB06_mine_excluded_nogc.mat',
             'AB07_mine_excluded_nogc.mat',
             'AB08_mine_excluded_nogc.mat',
             'AB09_mine_excluded_nogc.mat',
             'AB10_mine_excluded_nogc.mat',
             'AB11_mine_excluded_nogc.mat',
             'AB13_mine_excluded_nogc.mat',
             'AB12_mine_excluded_nogc.mat',
             'AB14_mine_excluded_nogc.mat',
             'AB15_mine_excluded_nogc.mat',
             'AB16_mine_excluded_nogc.mat',
             'AB17_mine_excluded_nogc.mat',
             'AB18_mine_excluded_nogc.mat',
             'AB19_mine_excluded_nogc.mat',
             'AB20_mine_excluded_nogc.mat',
             'AB21_mine_excluded_nogc.mat',
             'AB23_mine_excluded_nogc.mat',
             'AB24_mine_excluded_nogc.mat',
             'AB25_mine_excluded_nogc.mat',
             'AB27_mine_excluded_nogc.mat',
             'AB28_mine_excluded_nogc.mat',
             'AB30_mine_excluded_nogc.mat',
             ]

toe_side = ['rtoe', 'ltoe']

angles_tested = ['rankle',
                 'rsubt',
                 'rknee',
                 'rhip_addu',
                 'rhip_flex',
                 'rhip_rot',
                 'lankle',
                 'lsubt',
                 'lknee',
                 'lhip_addu',
                 'lhip_flex',
                 'lhip_rot',
                 ]

cycle_types = ['full',
               'swing',
               'stance',
               'nods',
               ]
